messages:
  configuration-reload: '&7La configuration a été rechargé.'
  # %author% -> Author name
  # %title% -> Book title
  apply-done: '&7La candidature &d%title%&7 a été envoyé.'
  errors:
    permission-denied: '&cVous n''avez pas la permission.'
    console-sender: '&cCette commande n''est pas utilisable depuis la console.'
    no-application: '&cAucune candidature n''est enregistrée.'
    item-not-book: '&cL''objet doit être un livre signé.'
  usages:
    look: '&cUtilisation : /quill look [joueur]'
    main: '&cUtilisation : /quill [apply|look|reload]'

menus:
  global:
    items:
      close: '&cQuitter'
      previous-page: '&7Page précédente'
      next-page: '&7Page suivante'
  all-players:
    title: '&7Candidatures'
    items:
      player-head:
        # %player% -> Author name
        # %title% -> Book title
        name: '&6%player%'
        # %player% -> Author name
        # %title% -> Book title
        # %date% -> Date of creation
        # %status% -> Book status
        # %pages% -> Pages number
        lore:
          - '&7Titre : %title%'
          - '&7Date : &d%date%'
          - '&7Status : &b%status%'
          - '&7Pages : &b%pages%'
  player:
    # %player% -> Player name
    # %size% -> Total size of player deaths on the server
    title: '&7Candidatures de &6%player%&7 (%size%)'
    items:
      book:
        # %title% -> Book title
        name: '&b%title%'
        # %date% -> Date of creation
        # %status% -> Book status
        # %pages% -> Pages number
        lore:
          - '&7Date : &d%date%'
          - '&7Status : &b%status%'
          - '&7Pages : &b%pages%'
  application:
    # %mount% -> Book title
    title: '&b%title%'
    items:
      waiting-color: '&e'
      accepted-color: '&a'
      refused-color: '&c'
      archived-color: '&8'

settings:
  status:
    waiting: "En attente"
    accepted: "Acceptée"
    refused: "Refusée"
    archived: "Archivée"

database:
  username: stuffrestoreruser
  password: 42)gZOgw.wd0z3tx
  name: devminecraft
  url: 'localhost:3306'