messages:
  configuration-reload: '&7Configuration has been reloaded.'
  # %author% -> Author name
  # %title% -> Book title
  apply-done: '&7Application &d%title%&7 has been submitted.'
  # %author% -> Author name
  notification-new-apply: '&7[&9Quill&7] &6%author%&7 just submitted a new application.'
  # %count% -> Applications count
  notification-on-join: '&7[&9Quill&7] &b%count%&7 applications are pending.'
  errors:
    permission-denied: '&cYou don''t have permission.'
    console-sender: '&cThis command cannot be used from the console.'
    no-application: '&cNo applications are registered.'
    no-application-self: '&cYou have not submitted any applications yet.'
    item-not-book: '&cThe item must be a signed book.'
    apply-failed: '&cFailed to submit your application. Please try again later.'
    # %player% -> Player not founded
    player-not-found: '&c%player% was not found.'
  usages:
    look: '&cUsage: /quill look <player>'
    main: '&cUsage: /quill [apply|look|reload|self]'

menus:
  global:
    items:
      close: '&cClose'
      back: '&7Back'
      previous-page: '&7Previous page'
      next-page: '&7Next page'
  all-players:
    title: '&7Applications'
    items:
      player-head:
        # %player% -> Author name
        # %title% -> Book title
        name: '&6%player%'
        # %player% -> Author name
        # %title% -> Book title
        # %date% -> Date of creation
        # %status% -> Book status
        # %pages% -> Pages number
        lore:
          - '&7Title: %title%'
          - '&7Date: &d%date%'
          - '&7Status: &b%status%'
          - '&7Pages: &b%pages%'
          - ''
          - '&7Right click to edit the status.'
          - '&7Left click to view the content.'
  player:
    # %player% -> Player name
    # %size% -> Total size of player deaths on the server
    title: '&7Applications of &6%player%&7 (%size%)'
    items:
      book:
        # %title% -> Book title
        name: '&b%title%'
        # %date% -> Date of creation
        # %status% -> Book status
        # %pages% -> Pages number
        lore:
          - '&7Date: &d%date%'
          - '&7Status: &b%status%'
          - '&7Pages: &b%pages%'
          - ''
          - '&7Right click to edit the status.'
          - '&7Left click to view the content.'
  application:
    # %mount% -> Book title
    title: '&b%title%'
    items:
      waiting-color: '&e'
      accepted-color: '&a'
      refused-color: '&c'
      archived-color: '&8'

settings:
  status:
    waiting: "Pending"
    accepted: "Accepted"
    refused: "Refused"
    archived: "Archived"

database:
  username: stuffrestoreruser
  password: 42)gZOgw.wd0z3tx
  name: devminecraft
  url: 'localhost:3306'

discord:
  webhook-url: ''