name: Quill
version: '${project.version}'
main: fr.loot1.quill.Quill
api-version: '1.19'
authors: [ Loot1 ]
commands:
  quill:
    description: Commande de gestion du plugin Quill
permissions:
  quill.*:
    description: Allows all permissions of Quill plugin
    default: op
    children:
      quill.apply: true
      quill.look: true
      quill.notify: true
      quill.reload: true
      quill.status: true
  quill.apply:
    description: Allows to apply
    default: op
  quill.look:
    description: Allows to look applications
    default: op
  quill.notify:
    description: Allows to have a notification if some applications are waiting
    default: op
  quill.reload:
    description: Allows to reload plugin configuration file
    default: op
  quill.status:
    description: Allows to change the status of an application
    default: op